.github/workflows/terraform-ci.yml

Keep align with other platforms

Remove test action and update go security generate

---

examples/resources/powermax_maskingview/resource.tf
powermax/models/masking_view.go
powermax/provider/host_data_source.go
powermax/provider/masking_view_data_source.go
powermax/provider/masking_view_resource.go
powermax/provider/masking_view_resource_test.go

Update masking view with OenAPI client
MaskingView

Update masking view with OenAPI client

---

docs/data-sources/host.md
docs/resources/host.md
docs/resources/maskingview.md
docs/resources/storagegroup.md
powermax/helper/helper.go
powermax/helper/storagegroup_helper.go
powermax/helper/volume_helper.go
powermax/models/volume.go
powermax/provider/volume_data_source.go
powermax/provider/volume_data_source_test.go
powermax/provider/volume_resource.go
powermax/provider/volume_resource_test.go

- Move Volume Datasource and Resource to OpenAPI
- 
Volume 
```
$ make check
terraform fmt -recursive examples/
gofmt -s -w .
golangci-lint run --fix --timeout 5m
go vet
```

Move Volumes to OpenAPI

---

powermax/helper/volume_helper.go
powermax/provider/host_data_source.go
powermax/provider/host_resource.go
powermax/provider/hostgroup_data_source.go
powermax/provider/hostgroup_resource.go
powermax/provider/masking_view_data_source.go
powermax/provider/masking_view_resource.go
powermax/provider/portgroup_data_source.go
powermax/provider/storagegroup_data_source.go
powermax/provider/storagegroup_resource.go
powermax/provider/storagegroup_resource_test.go
powermax/provider/volume_data_source.go
powermax/provider/volume_resource.go

- Move all of the uses of error processing to use the method instead of implementing there own error handling.
All.
Ran all tests
```
make check
terraform fmt -recursive examples/
gofmt -s -w .
golangci-lint run --fix --timeout 5m
go vet
```

Update Error Path

---

powermax/provider/portgroup_data_source.go

Handle NPE for filter value
portgroup datasource
```paste below
```
```paste below
```

Update portgroup datasource to handle filter type

---

docs/resources/hostgroup.md
powermax/helper/host_helper.go
powermax/helper/hostgroup_helper.go
powermax/provider/hostgroup_resource.go

Add validator for hostgroup
| |
Hostgroups
```paste below
```
```paste below
```

Add validators for hostgroups

---

powermax/helper/port_helper.go

Fix nil check issue for optional Port Values
Port Datasource

Nil check Port Optional Values

---

docs/data-sources/storagegroup.md
docs/resources/storagegroup.md
examples/data-sources/powermax_storagegroup/data-source.tf
powermax/helper/storagegroup_helper.go
powermax/provider/storagegroup_data_source.go
powermax/provider/storagegroup_resource.go

- While writing the automation for the functional testing of the Storage Group datasource and resource. These issues were found and fixed.
StorageGroup

Storage Group FT Fixs

---

docs/resources/host.md
powermax/provider/host_resource.go

- Small  updates to hosts resource after the creation of the functional automation tests. 
Host resource and datasource

Fixes after FT run

---

powermax/provider/masking_view_resource.go

- Minor changes to fix issues found during the functional test automation creation. 

Masking View FT fixes

---

powermax/provider/snapshotpolicy_resource.go

After writing the functional tests for Snapshot policy, needed to make this change in order for all the tests to pass.
Snapshot Policy

Snapshot Policy FT fixes

---

docs/resources/volume.md
powermax/helper/volume_helper.go
powermax/provider/volume_resource.go
powermax/provider/volume_resource_test.go

- A few minor fixes after writing the volumes Functional Tests. 
Volume

Volume FT fixes

---

powermax/helper/helper.go
powermax/provider/snapshot_data_source.go
powermax/provider/snapshot_resource_test.go

Snapshot FTs updates
| |
- Test Pull Request
Snapshot

Changes for Snapshot FTs

---

docs/resources/snapshot.md
examples/resources/powermax_snapshot/resource.tf
powermax/helper/snapshot_helper.go
powermax/models/snapshot.go
powermax/provider/snapshot_resource.go

- Remove the Snapshot Action SetMode, since it does the same thing as link snapshot.
Snapshot

Remove Snapshot SetMode

---

powermax/helper/snapshot_helper.go
powermax/provider/port_datasource.go

Fix failures for Snapshot and Port which occurred due to some recent PR merges.
| |
Snapshot Resource and Port Datasource
```paste below
```

Fix failures for Snapshot and Port

---

go.mod
go.sum
powermax/helper/helper.go
powermax/helper/storagegroup_helper.go
powermax/provider/storagegroup_resource.go

Remove the last of the references to gopowermax.
NA

Remove GoPowerMax References

---

about/ATTRIBUTION.md

Add attribution with includes libraries
None
N/A
```
```

Add attribution file

---

client/client.go

- Reduce the timeout for any single request to be 60 seconds.
NA

Reduce Timeout to 60s

---

CHANGELOG.md
README.md

Fix the readme and changelog formatting issues
| |
```paste below
```
```paste below
```

Update Readme and Changelog

---

client/client.go
powermax/helper/helper.go
powermax/helper/host_helper.go
powermax/helper/portgroup_helper.go

- There were some low priority flags Checkmarks found. They were fixed in this PR.
Many

Fix Low Priorty Checkmarks

---

docs/data-sources/host.md
docs/data-sources/hostgroup.md
docs/data-sources/maskingview.md
docs/resources/host.md
docs/resources/hostgroup.md
docs/resources/maskingview.md
examples/resources/powermax_host/resource.tf
examples/resources/powermax_hostgroup/resource.tf
examples/resources/powermax_maskingview/resource.tf
powermax/provider/host_data_source.go
powermax/provider/host_resource.go
powermax/provider/hostgroup_data_source.go
powermax/provider/hostgroup_resource.go
powermax/provider/masking_view_data_source.go
powermax/provider/masking_view_resource.go

After review a few more doc updates were needed for the 1.0.0 release of PowerMax
Doc

PowerMax Doc Updates

---

go.mod
go.sum

Update mockey to v1.2.9
A few sentences describing the overall goals of the pull request's commits.
| |
- Test Pull Request
```paste below
```
```paste below
```

Update mockey version

---

README.md

PowerMax Patch Version Update

---

go.mod
go.sum
powermax/provider/provider_test.go

Updated the go sum and go mod files to correspond with blackduck scan
- Security Pull Request

updated security (black duck scan)

---

README.md
about/ATTRIBUTION.md

Updated Attribution file and Readme to reflect v1.0.3

Updated Attirbution and Readme documentation

---

docs/guides/provider_example.md
docs/index.md
powermax/provider/provider.go
templates/guides/provider_example.md

- Update Endpoint docs for more clarity
- NA this is just a doc update

Add clarification to endpoint variable
